task 2
sharksystems/rentzila-playwright pull request #2
Opened 2024-09-23 11:40 UTC by sharksystems

2024-10-01 14:27 UTC, Vaas-d commented
Good PR **must always** contain a description. Otherwise, no one will understand why they should merge your work into a common project. (see. https://gist.github.com/mikepea/863f63d6e37281e329f8)

2024-10-01 14:43 UTC, Vaas-d requested changes
See the comments, especially one regarding the PR description

2024-10-01 14:43 UTC, Vaas-d commented on data/ErrorMessages.ts
> +    PASSWORD_INVALID_FORMAT = "Пароль повинен містити як мінімум 1 цифру, 1 велику літеру і 1 малу літеру, також не повинен містити кирилицю та пробіли"
Why all upper case and not camelCase? These are not env. vars. The separation with an underscore is typical to Python and not JS/TS.

2024-10-01 14:43 UTC, Vaas-d commented on page_elements/FooterElements.ts
>      private cookiesPolicyLink() { return this.page.getByTestId('pravila-vikoristannya-failiv-cookie'); }
1. Is there a specific reason you are not placing your locators into a class constructor?
2. What's the purpose of wrapping your locators into separate getter functions instead of using the approach recommended by Playwright docs?
Reference https://playwright.dev/docs/pom

2024-10-01 14:43 UTC, Vaas-d commented on page_elements/HeaderElements.ts
> +    private userDropdownLogoutBtn() { return this.page.getByTestId('logout'); }
1. Is there a specific reason you are not placing your locators into a class constructor?
2. What's the purpose of wrapping your locators into separate getter functions instead of using the approach recommended by Playwright docs?
Reference https://playwright.dev/docs/pom

2024-10-01 14:43 UTC, Vaas-d commented on page_elements/LoginPopup.ts
> +    private loginCredentialsErrorMsg() { return this.page.getByTestId('errorMessage'); }
1. Is there a specific reason you are not placing your locators into a class constructor?
2. What's the purpose of wrapping your locators into separate getter functions instead of using the approach recommended by Playwright docs?
Reference https://playwright.dev/docs/pom

2024-10-01 14:43 UTC, Vaas-d commented on pages/MyProfilePage.ts
> +    private phoneVerificationStatus = this.page.getByTestId("verification_OwnerProfileNumber");
Is there a specific reason you are not placing your locators into a class constructor?

2024-10-01 14:43 UTC, Vaas-d commented on data/LoginData.ts
> +        this.password = process.env.VALID_PASSWORD || 'VALID_PASSWORD';
What's the purpose of hiding your env. vars. in a class constructor? Wouldn't it be better to initialize them as global variables in your tests and not call the getter methods every time you need to use them??

2024-10-01 14:43 UTC, Vaas-d commented on tests/login.spec.ts
> +    test('Login with email or password missing', async ({ homePage, headerElements, loginData, loginPopup }) => {
Here and after: Where are the IDs of your tests? Surely your TCs have IDs.

2024-10-01 14:43 UTC, Vaas-d commented on tests/login.spec.ts
> +        await headerElements.clickLoginBtn();
Why don't you move this method (await headerElements.clickLoginBtn();) into a beforeEach block to avoid code duplicates, since each of your tests starts with this step?

2024-10-01 14:43 UTC, Vaas-d commented on tests/login.spec.ts
> +        await myProfilePage.assertUserPhonePrefilledAndVerified(loginData.phoneWithSpaces);
Aren't these negative scenarios?? If true, then what are they doing in test named 'Login with valid phone number and password'???

2024-10-01 14:43 UTC, Vaas-d commented on tests/login.spec.ts
> +        await loginPopup.assertEmailOrPhoneErrorVisibleWithText(ErrorMessages.EMAIL_OR_PHONE_INVALID_FORMAT);
It is better to split such checks into different test entities because if the first one fails you will not be able to test the rest of the scenarios.

2024-10-01 14:43 UTC, Vaas-d commented on tests/login.spec.ts
> +        await loginPopup.assertLoginPopupVisible();
It is better to split such checks into different test entities because if the first one fails you will not be able to test the rest of the scenarios.

2024-10-01 14:43 UTC, Vaas-d commented on tests/login.spec.ts
> +        await loginPopup.assertLoginCredentialsErrorMsg(ErrorMessages.WRONG_EMAIL_OR_PASSWORD);
It is better to split such checks into different test entities because if the first one fails you will not be able to test the rest of the scenarios.

2024-10-01 14:43 UTC, Vaas-d commented on tests/login.spec.ts
> +        await loginPopup.assertLoginCredentialsErrorMsg(ErrorMessages.WRONG_EMAIL_OR_PASSWORD);
It is better to split such checks into different test entities because if the first one fails you will not be able to test the rest of the scenarios.

2024-10-02 10:59 UTC, sharksystems commented on data/ErrorMessages.ts
> +    PASSWORD_INVALID_FORMAT = "Пароль повинен містити як мінімум 1 цифру, 1 велику літеру і 1 малу літеру, також не повинен містити кирилицю та пробіли"
UPPER_SNAKE_CASE is a widely accepted norm for naming constants across many languages, which also carried over to JS/TS
However, i dont see this format being enforced in any official JS/TS docs, so it really depends on the [style guide](https://github.com/airbnb/javascript/#naming--uppercase) of a project. So we can decide which format fits best.
I can agree with having the names be in camelCase, as it will look more consistent with the rest of the project.

2024-10-02 11:11 UTC, sharksystems commented on page_elements/FooterElements.ts
>      private cookiesPolicyLink() { return this.page.getByTestId('pravila-vikoristannya-failiv-cookie'); }
1. I decided to try declaring locators directly because in TS, you need to declare variables first before you assign the value in the constructor, which results in 2x lines of code.
2. Declaring locators directly only works for pages that inherit from BasePage, otherwise TS complains about the page instance being used before it is initialized. Implementing locators as a method is a workaround for that,

Though having 2 different ways to declare locators in the project doesnt look very good, so i will go back to using the recommended Playwright approach.

2024-10-02 11:23 UTC, sharksystems commented on data/LoginData.ts
> +        this.password = process.env.VALID_PASSWORD || 'VALID_PASSWORD';
I made these as class properties not only to use the valid data in tests, but also to use in the methods of the class that parse those values in different format for negative tests. Which if i understood correctly was required in the test cases (the credentials must be for a registered user)

2024-10-02 18:24 UTC, sharksystems commented on tests/login.spec.ts
> +        await myProfilePage.assertUserPhonePrefilledAndVerified(loginData.phoneWithSpaces);
Phone number without plus or the country code should be accepted by the login form, so positive scenarios
![image](https://github.com/user-attachments/assets/ee416f89-06dc-40cb-8466-506aaec378ef)

2024-10-03 16:42 UTC, Vaas-d commented on tests/login.spec.ts
> +        await myProfilePage.assertUserPhonePrefilledAndVerified(loginData.phoneWithSpaces);
Ok, agreed, but again it is better to split such checks into different test entities because if the first one fails you will not be able to test the rest of the scenarios.

2024-10-04 08:52 UTC, sharksystems commented on tests/login.spec.ts
> +        await myProfilePage.assertUserPhonePrefilledAndVerified(loginData.phoneWithSpaces);
Fixed in the commit
![image](https://github.com/user-attachments/assets/24a19b50-a382-4744-b332-3774ac4244cc)

2024-10-05 07:45 UTC, Vaas-d approved these changes

2024-10-06 19:05 UTC, merged