task 4
sharksystems/rentzila-playwright pull request #4
Opened 2024-10-10 15:14 UTC by sharksystems

Added test cases C384, C401, C405, C390, C393, C593, C594, C595, C593, C594, C595

2024-10-16 15:02 UTC, AndreyCar requested changes

2024-10-16 15:02 UTC, AndreyCar commented on tests/unit_creation.spec.ts
> +        (await unitCreationPage.getTabTitleByNumber(1)).click();
Remove these brackets

2024-10-16 15:02 UTC, AndreyCar commented on tests/unit_creation.spec.ts
> +        (await unitCreationPage.getTabTitleByNumber(1)).click();
Remove these brackets

2024-10-16 15:02 UTC, AndreyCar commented on tests/unit_creation.spec.ts
> +        (await unitCreationPage.getTabTitleByNumber(1)).click();
Remove these brackets

2024-10-16 15:02 UTC, AndreyCar commented on tests/unit_creation.spec.ts
> +        (await unitCreationPage.getTabTitleByNumber(1)).click();
Remove these brackets

2024-10-16 15:02 UTC, AndreyCar commented on tests/unit_creation.spec.ts
> +        (await unitCreationPage.getTabTitleByNumber(1)).click();
Remove these brackets

2024-10-16 15:02 UTC, AndreyCar commented on tests/unit_creation.spec.ts
> +        (await unitCreationPage.getTabTitleByNumber(1)).click();
Remove these brackets

2024-10-16 15:02 UTC, AndreyCar commented on tests/unit_creation.spec.ts
> +        (await unitCreationPage.getTabTitleByNumber(1)).click();
Remove these brackets

2024-10-16 17:35 UTC, sharksystems commented on tests/unit_creation.spec.ts
> +        (await unitCreationPage.getTabTitleByNumber(1)).click();
getTabTitleByNumber and similar methods didnt really need to be asynchronous, fixed in the commit

2024-10-21 08:43 UTC, AndreyCar approved these changes

2024-10-21 10:29 UTC, merged