task 8
sharksystems/rentzila-playwright pull request #7
Opened 2024-11-05 13:09 UTC by sharksystems

Added API request for creating a Unit and actions for interacting with it. Also added a test that verifies the Unit Created via API

2024-11-09 04:55 UTC, Vaas-d requested changes
See the comments below

2024-11-09 04:55 UTC, Vaas-d commented on helpers/ApiHelper.ts
> +            await this.request.post("https://dev.rentzila.com.ua/api/auth/jwt/create/", {
In real project you'd like to hide various sensitive data (like URL or at least this part https://dev.rentzila.com.ua/api) into an environment variable.
1. It protects sensitive data from possible exposure
2. It reduces duplication (you use https://dev.rentzila.com.ua/api 7 times in your code)
3. in case of multiple test environments this makes easier to set up the env to use

2024-11-09 04:55 UTC, Vaas-d commented on helpers/ApiHelper.ts
> +            await this.request.post("https://dev.rentzila.com.ua/api/auth/jwt/create/", {
This env.var. can be stored as a global const to be used in this functions

2024-11-09 04:55 UTC, Vaas-d commented on helpers/ApiHelper.ts
> +        }
It would be good to generate random data where possible

2024-11-09 04:55 UTC, Vaas-d commented on tests/unit_creation_api.spec.ts
> +        let unitId = await apiHelper.createUnit(accessToken, unitName, 'valid_jpeg.jpeg');
Looks like this part is a test setup. Why don't you put it into the before block?

2024-11-09 04:55 UTC, Vaas-d commented on tests/unit_creation_api.spec.ts
> +        await apiHelper.deleteUnit(adminAccessToken, unitId);
And this part looks like a teardown, so it might be better to place it into the after block

2024-11-09 15:18 UTC, sharksystems commented on helpers/ApiHelper.ts
> +            await this.request.post("https://dev.rentzila.com.ua/api/auth/jwt/create/", {
Thanks, i already had and env var for base url but forgot to use it here

2024-11-09 15:19 UTC, sharksystems commented on helpers/ApiHelper.ts
> +        }
As of right now we need to have the unit name randomized, and i usually define the values in the tests

2024-11-09 15:20 UTC, sharksystems commented on tests/unit_creation_api.spec.ts
> +        let unitId = await apiHelper.createUnit(accessToken, unitName, 'valid_jpeg.jpeg');
There is only 1 test here right now, but i can reuse the setup/teardown from my later tests

2024-11-13 03:55 UTC, Vaas-d approved these changes

2024-11-13 03:55 UTC, Vaas-d commented on helpers/ApiHelper.ts
> +        }
OK, no problem

2024-11-13 03:57 UTC, Vaas-d commented on tests/unit_creation_api.spec.ts
> +        let unitId = await apiHelper.createUnit(accessToken, unitName, 'valid_jpeg.jpeg');
It is better to exercise a proactive approach, especially on quickly developed projects.

2024-11-13 11:40 UTC, merged